config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    # 장고가 ""인 주소를 보면 , core.urls 로  들어간다
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls",
                                  namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/",
         include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/delete/", views.delete_room, name="delete-room"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotosView.as_view(), name="add-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photo",),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views


app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao-callback"),
    path("login/google/", views.google_login, name="google-login"),
    path("login/google/callback/", views.google_callback, name="google-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>/", views.complete_verification, name="complete-verification"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswowdView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
]

templates/partials/footer.html
{% load i18n %}
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-500">
    <div class="flex flex-col">
        <span>
            {% trans "무단 복제를 금지합니다." %}
        </span>
        <span>&copy; 2020 MYbnb , Inc. {% trans '이 사이트의 모든 저작권은 MYbnb 가 소유하고 있습니다 ' %}</span>
    </div>
    <div class="mt-10 flex">
        {% get_current_language as LANGUAGE_CODE %}
        <!-- https://docs.djangoproject.com/en/3.0/topics/i18n/translation/ 참조 -->
        
        <select class="w-1/5 h-8" id="js-lang">
            <option value="ko""
                {% if LANGUAGE_CODE == 'ko' %}
                selected
                {% endif %}
            >한국어</option>
            <option value="en"
                {% if LANGUAGE_CODE == 'en' %}
                    selected
                {% endif %}
            >English</option>
            <option value="cn""
            {% if LANGUAGE_CODE == 'cn' %}
            selected
            {% endif %}
            >汉语</option>
</footer>

templates/partials/messages.html
{% if messages %}
<ul class="absolute top-0 mx-auto left-0 right-0  flex justify-center">
    {% for message in messages %}
        <li class="message font-medium bg-gray-700 z-10 rounded-full text-white py-4 px-6  w-80 text-center {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
<ul class="flex items-center text-sm font-bold h-full">
    {% if user.is_authenticated %}
    <!-- 장고의 컨텍스트 프로세서가 작동하여 쿠키를 가져와 유저를 찾고 그걸 템플릿에 자동으로 입력해줌 -->
    <li class="nav_link">
        <a href="{% url 'users:switch-hosting' %}">
            {% if request.session.is_hosting %}
                호스팅 종료
            {% else %}
                호스팅 시작
            {% endif %}

        </a>
    </li>
   
    {% if request.session.is_hosting %}
    <li class="nav_link"><a href="{% url 'rooms:create' %}">객실 등록</a></li>
    {% endif %}
    <li class="nav_link"><a href="{% url 'lists:see-favs' %}">관심목록 ({{user.lists.rooms.count}})</a></li>
    <li class="nav_link"><a href="{{user.get_absolute_url}}">내정보</a></li>
    <li class="nav_link"><a href="{% url 'users:logout' %}">로그아웃</a></li>
    {% else %}
    <li class="nav_link"><a href="{% url 'users:login' %}">로그인</a></li>
    <li class="nav_link"><a href="{% url 'users:signup' %}">회원가입</a></li>
    {% endif %}
</ul>

templates/partials/social_login.html
<div class="flex flex-col w-full">
 
    <a href="{% url 'users:kakao-login' %}" class="btn border border-2 border-yellow-400 text-gray-800 mb-2 bg-yellow-400">
        <i class="fas fa-comment mr-2 fa-lg"></i>카카오로 로그인하기
    </a>
    <a href="{% url 'users:google-login' %}" class="btn border border-2 border-gray-700 text-gray-700 mb-2 ">
        <i class="fab fa-google text-red-700 mr-2 fa-lg"></i>구글로 로그인하기
    </a>
    <a href="{% url 'users:github-login' %}" class="btn border border-2 border-gray-700 text-white  mb-2  bg-gray-700">
        <i class="fab fa-github text-white mr-2 fa-lg"></i>깃허브로 로그인하기
    </a>
</div>

<div class="flex items-center w-full my-5">
    <div class="h-px w-full bg-gray-500 "></div>
    <span class="text-gray-700 font-bold mx-4 text-sm">OR</span>
    <div class="h-px w-full bg-gray-500 "></div>
</div>