config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    # 장고가 ""인 주소를 보면 , core.urls 로  들어간다
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls",
                                  namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/",
         include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/delete/", views.delete_room, name="delete-room"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotosView.as_view(), name="add-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photo",),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django_countries.fields import CountryField
from core import models as core_models
from cal import Calendar


# from users import models as user_models , "users.User" 로 불러올경우 따로 임포트를 안해줘도 된다

# Create your models here.


class AbstractItem(core_models.TimeStampedModel):

    """ Abstract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


# 방종류 ,편의시설 , 시설 등등에서 사용할것이기에 추상 아이템을 만들어준다


class RoomType(AbstractItem):
    class Meta:
        verbose_name_plural = "객실종류"
        ordering = ["name"]  # 각종 정렬기준을 넣을수 있는데 예를들어 -name 일 경우는 역순으로 정렬


class Amenity(AbstractItem):
    class Meta:
        verbose_name_plural = "편의시설"
        ordering = ["name"]


class Facility(AbstractItem):
    class Meta:
        verbose_name_plural = "시설"
        ordering = ["name"]


class HouseRule(AbstractItem):
    class Meta:
        verbose_name_plural = "이용규칙"
        ordering = ["name"]


class Photo(core_models.TimeStampedModel):
    """ 포토 모델 정의 """

    caption = models.CharField(verbose_name="설명", max_length=80)
    file = models.ImageField(
        verbose_name="파일", upload_to="room_photos", blank=True)
    room = models.ForeignKey(
        "Room", verbose_name="객실", related_name="photos", on_delete=models.CASCADE
    )
    # room = models.ForeignKey(Room, on_delete=models.CASCADE) 로 작성할경우 , 위에서 아래로 코드를 읽고 수행하기에
    # 룸 클래스를 제대로 가져오지 못한다

    def __str__(self):
        return self.caption

    class Meta:
        verbose_name = "사진"
        verbose_name_plural = "사진"


class Room(core_models.TimeStampedModel):

    """ 룸 모델 정의 """

    name = models.CharField(verbose_name="이름", max_length=140)
    description = models.TextField(verbose_name="설명")
    country = CountryField(verbose_name="국가")
    city = models.CharField(verbose_name="도시", max_length=80)
    price = models.IntegerField(verbose_name="가격")
    address = models.CharField(verbose_name="주소", max_length=140)
    guests = models.IntegerField(verbose_name="숙박인원", default=0)
    beds = models.IntegerField(verbose_name="침대")
    bedrooms = models.IntegerField(verbose_name="침실")
    baths = models.IntegerField(verbose_name="욕실")
    check_in = models.TimeField(verbose_name="체크인 시간")
    check_out = models.TimeField(verbose_name="체크아웃 시간")
    instant_book = models.BooleanField(verbose_name="즉시예약", default=False)
    host = models.ForeignKey(
        "users.User", verbose_name="호스트", related_name="rooms", on_delete=models.CASCADE
    )  # 하나만 선택가능, related_name 을 설정함으로서 외래키가 가리키는 대상에서 역으로 호출을 할수있다
    # users.User 는 room_set 을 가지고 있어서 related_name 으로 역으로 사용가능하다
    room_type = models.ForeignKey(
        "RoomType", verbose_name="객실종류", related_name="rooms", on_delete=models.SET_NULL, null=True,
    )
    # ForeignKey가 바라보는값 이 삭제될때 필드의 값을 null 로 바꾼다
    amenities = models.ManyToManyField(
        "Amenity", verbose_name="편의시설", related_name="rooms", blank=True
    )
    facilities = models.ManyToManyField(
        "Facility", verbose_name="시설", related_name="rooms", blank=True
    )
    house_rules = models.ManyToManyField(
        "HouseRule", verbose_name="이용규칙", related_name="rooms", blank=True
    )

    # reservations = models.ForeignKey(
    #     "reservations.Reservation",
    #     verbose_name="예약상황",
    #     related_name="rooms",
    #     on_delete=models.CASCADE,
    #     null=True,
    # )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save()

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})
        # get_absolute_url 메소드로 디테일뷰에 pk 값을 전달해준다

    def total_rating(self):

        all_reviews = self.reviews.all()
        # related_name 으로 리뷰와 연결되어 있다 , 모든 리뷰들을 가져와라

        all_ratings = 0
        for review in all_reviews:
            all_ratings += review.rating_average()
            # review.rating_average() ->review 에있는 rating_average함수 호출

        if all_ratings == 0:
            return 0

        else:
            return round(all_ratings / len(all_reviews), 2)

    total_rating.short_description = "평균점수"

    # 리뷰에 있는 모든 개인별 평정을 가지고 와서 총 평점을 구한다

    class Meta:
        verbose_name = "객실"
        verbose_name_plural = "객실"

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_next_four_photos(self):
        photos = self.photos.all()[1:5]

        return photos

    def get_calendars(self):
        now = timezone.now()
        this_year = now.year
        next_year = this_year
        this_month = now.month
        next_month = this_month + 1
        str_this_month = str(this_month)
        if this_month == 12:
            next_month = 1
            next_year = this_year + 1
        this_month_cal = Calendar(this_year, this_month)
        next_month_cal = Calendar(next_year, next_month)
        return [this_month_cal, next_month_cal]

        # 이미 만들어진 cal.py에 시간을 지정하여 템플릿에 전달해주는 방법을 정하는 메쏘드 이다

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(label="도시", initial="장소를 입력 하세요", required=False)
    country = CountryField(default="KR").formfield(label="국가")
    price = forms.IntegerField(label="가격", required=False)
    room_type = forms.ModelChoiceField(
        required=False,
        label="객실종류",
        empty_label="객실을 선택 하세요",
        queryset=models.RoomType.objects.all(),
    )
    guests = forms.IntegerField(label="숙박인원", required=False)  # help_text="숙박 인원의 수를 입력하세요",
    beds = forms.IntegerField(label="침대갯수", required=False)
    bedrooms = forms.IntegerField(label="침실수", required=False)
    baths = forms.IntegerField(label="욕실수", required=False)
    instant_book = forms.BooleanField(label="즉시예약", required=False)
    superhost = forms.BooleanField(label="슈퍼호스트", required=False)
    amenities = forms.ModelMultipleChoiceField(
        label="편의시설",
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    facilities = forms.ModelMultipleChoiceField(
        label="시설",
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    print(amenities)

    def clean(self):
        amenities = self.cleaned_data.get("amenities")
        print(self.cleaned_data)
        return self.cleaned_data


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):

        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()
        # form 에게 오브젝트를 생성하라는 뜻이기도 하다
        # room 객체의 pk 가 필요한데 form 에서는 받아올 방법이 없다 , 뷰에서 form_valid 를 통해 받아오도록 한다


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        # 룸을 생성만함 (유저는 없음)
        return room
        # 그리고 리턴 => view 에서 처리

rooms/views.py
from django.http import Http404
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.shortcuts import render, redirect, reverse
from django_countries import countries
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from users import mixins as user_mixins
from . import models, forms


class HomeView(ListView):

    """홈뷰의 정의"""

    # http://ccbv.co.uk/projects/Django/3.0/django.views.generic.list/ListView/ 참조

    # 템플릿 네임을 지정하지 않을경우 장고 어드민에서 시키는대로 지정을 해줘도 된다
    model = models.Room
    paginate_by = 12
    paginate_orphans = 6
    ordering = "created"
    page_kwarg = "page"
    context_object_name = "rooms"


# def room_detail(request, pk):

#     try:
#         room = models.Room.objects.get(pk=pk)
#         return render(request, "rooms/detail.html", {"room": room})
#     except models.Room.DoesNotExist:
#         raise Http404()


class RoomDetail(DetailView):

    """ 룸 자세히 보기 정의 """

    model = models.Room


class SearchView(View):
    def get(self, request):

        country = request.GET.get("country")

        if country:

            form = forms.SearchForm(request.GET)

            if form.is_valid():
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "장소를 입력 하세요":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["host__superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity
                    # cleaned_data 를 거쳐서 오기때문에 __pk 로 필터링을 할 필요가 없다

                for facility in facilities:
                    filter_args["facilities"] = facility

                qs = models.Room.objects.filter(**filter_args).order_by("created")
                paginator = Paginator(qs, 5)
                page = request.GET.get("page", 1)
                rooms = paginator.get_page(page)
                query_string = request.environ.get("QUERY_STRING")
                # 쿼리스트링을 활용해서 입력된 주소를 기억할수 있다

                return render(
                    request,
                    "rooms/search.html",
                    {"form": form, "rooms": rooms, "query_string": query_string},
                )

            # request.GET 으로 무엇을 입력했는지 기억 한다
        else:
            form = forms.SearchForm()
            # 처음 페이지를 열었을때 폼을 받아오는 부분

            return render(request, "rooms/search.html", {"form": form})


class EditRoomView(user_mixins.LoggedInOnlyView, UpdateView):

    model = models.Room
    template_name = "rooms/room_edit.html"
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        # 현재 보고있는 룸을 찾는다
        if room.host.pk != self.request.user.pk:
            # 룸 호스트의 pk 와 접속한 유저의 pk를 비교한다
            raise Http404("페이지를 찾을수 없습니다")
        return room


class RoomPhotosView(user_mixins.LoggedInOnlyView, DetailView):

    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):

        room = super().get_object(queryset=queryset)

        if room.host.pk != self.request.user.pk:
            raise Http404("페이지를 찾을수 없습니다")
        return room


@login_required
# 로그인 하지 않을경우 setting.LOGIN_URL 로 이동
# fbv 이기 때문에 데코레이터 사용 , cbv 일때는 믹스인 상속
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "사진을 삭제할 수 없습니다")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "사진을 삭제 하였습니다")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))

    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):
    # 업데이트뷰는 pk값만을 찾기에 따로 지정을 해줘야한다

    model = models.Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    # pk 말고 photo_pk 를 찾아라
    success_message = "사진 업데이트 성공"
    fields = ("caption",)

    def get_success_url(self):
        # 수정 성공시 돌아갈 url
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class AddPhotosView(user_mixins.LoggedInOnlyView, FormView):

    template_name = "rooms/photo_create.html"

    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        user_pk = self.request.user.pk
        room = models.Room.objects.get(pk=pk)
        host_pk = room.host.pk
        if host_pk != user_pk:
            raise Http404("페이지를 찾을수 없습니다")
        else:
            form.save(pk)
        # form에 room의 pk 값을 전달해준다
        messages.success(self.request, "사진이 업로드 되었습니다")
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save()
        # 폼에서 생성된 룸을 저장
        room.host = self.request.user
        # 룸의 호스트는 현재 작성자
        room.save()
        # 룸 저장
        form.save_m2m()
        # 다대다 필드 저장=>  m2m 필드를 저장할때 데이터베이스에 저장한후에 사용가능하다
        messages.success(self.request, "객실이 등록 되었습니다")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))


@login_required
def delete_room(request, pk):
    user = request.user

    try:
        room = models.Room.objects.get(pk=pk)
        if room.host.pk != user.pk:
            messages.error(request, "객실을 삭제할 수 없습니다")
        else:
            room.delete()
            messages.success(request, "객실을 삭제 하였습니다")
        return redirect(reverse("core:home"))
    except room.DoesNotExist:
        return redirect(reverse("core:home"))

templates/rooms/photo_create.html
{% extends "base.html" %}

{% block page_title %}
사진 업로드
{% endblock page_title %}

{% block search-bar %}

{% endblock search-bar %}



{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
  
    {% include 'mixins/room/room_form.html' with form=form cta="사진 업로드" %}

</div>
{% endblock content %}

templates/rooms/photo_edit.html
{% extends "base.html" %}

{% block page_title %}
사진정보 수정
{% endblock page_title %}

{% block search-bar %}

{% endblock search-bar %}

<!-- 베이스 탬플릿에 있는 서치바를 숨겨준다 -->

{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
  
    {% include 'mixins/room/room_form.html' with form=form cta="사진정보 수정" %}

</div>
{% endblock content %}

<!-- 플레이스 홀더를 입력하려면 직접 폼을 커스텀해야한다  -->

templates/rooms/room_create.html
{% extends "base.html" %}

{% block page_title %}
객실 등록
{% endblock page_title %}

{% block search-bar %}

{% endblock search-bar %}



{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
  
    {% include 'mixins/room/room_form.html' with form=form cta="객실등록" %}

</div>
{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %}

{% load is_booked on_favs i18n %}

{% block page_title %}
{{room.name}}
{% endblock page_title %}

{% block content %}
    <div class="container max-w-full h-75vh flex mb-20">
        <div class="h-full w-1/2 bg-center bg-cover" style="background-image:url({{room.first_photo}})"></div>
        <div class="h-full w-1/2 flex flex-wrap">
            {%for photo in room.get_next_four_photos %}
             <div style="background-image:url({{photo.file.url}})" class="w-1/2 h-auto bg-cover bg-center border-gray-700 border"></div>
            {% endfor %}
        </div>
    </div>

    <div class="container mx-auto flex justify-around pb-56">
        <div class="w-1/2">
            <div class="flex justify-between">
                <div class="mb-5">
                    <h4 class="text-3xl font-medium mb-px">{{room.name}}</h4>
                    <span class="text-gray-700 font-light">{{room.city}}</span> 
                </div>
                <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user=room.host %}
                    <span class="mt-2 text-gray-500">{{room.host.username}}</span>
                </a>
            </div>
            {% if user.is_authenticated %}
                {% on_favs room  as on_favs_boolean %}
                {% if on_favs_boolean %}
                <a class="block mb-10 w-2/6 text-teal-600 font-bold" href="{% url 'lists:toggle-room' room.pk %}?action=remove">{% trans "관심목록에서 제거" %}</a>
                {% else %}
                    <a class="block mb-10 w-2/6 text-teal-600 font-bold" href="{% url 'lists:toggle-room' room.pk %}?action=add">{% trans "관심목록에 추가" %}</a>
                {% endif %}
            {% endif %}
                <div class="flex border-section">
                    <span class="mr-5 font-light">{{room.room_type}}</span>
                    <span class="mr-5 font-light">·최대인원 {{room.guests}}명</span>
                    <span class="mr-5 font-light">·침실 {{room.bedrooms}}개</span>
                    <span class="mr-5 font-light">·침대 {{room.beds}}개</span>
                    <span class="mr-5 font-light">·욕실 {{room.baths}}개</span>
                </div>
                <p  class="border-section">
                    {{room.description}}
                </p>
                <div class="border-section">
                    <h4 class="font-medium text-lg mb-5">편의시설</h4>
                    {% for a in room.amenities.all %}
                        <li class="mb-2">{{a}}</li>
                    {% endfor %}
                </div>
                <div class="border-section">
                    <h4 class="font-medium text-lg mb-5">시설</h4>
                    {% for f in room.facilities.all %}
                        <li class="mb-2">{{f}}</li>
                    {% endfor %}
                </div>
                <div class="border-section">
                    <h4 class="font-medium text-lg mb-5">이용규칙</h4>
                    {% for r in room.house_rules.all %}
                        <li class="mb-2">{{r}}</li>
                    {% endfor %}
                </div>
                <div class="mt-10">
                    <h4 class="font-medium text-2xl mb-5">리뷰</h4>
                    <div class="flex items-center">
                        <div>
                            <i class="fas fa-star text-teal-500"></i>
                            <span class="font-bold text-xl">{{room.total_rating}}</span>
                        </div>
                        <div class="h-4 w-px bg-gray-400 mx-5"></div>
                        <div>
                            <span class="font-bold text-xl">{{room.reviews.count}}</span>
                            <span>review{{room.reviews.count|pluralize}}</span>
                        </div>
                    </div>
                    <div class="mt-10">
                        {% for review in room.reviews.all  %}
                            <div class="border-section">
                                <div class="mb-3 flex">
                                    <div>
                                        {% include "mixins/user_avatar.html" with user=review.user h_and_w='w-10 h-10' text='text-xl' %}
                                    </div>
                                    <div class="flex flex-col ml-5">
                                        <span class="font-medium">{{review.user.username}}</span>
                                        <span class="text-sm text-gray-500">{{review.created|date:'Y F'}}</span>
                                    </div>
                                </div>
                                <p>{{review.review}}</p>
                            </div>
                        {% endfor %}    
                    </div>
                </div>
            </div>
        <div class="w-1/3">
            {% if room.host == user %}
                <div>
                    <a href="{% url 'rooms:edit' room.pk %}" class="btn-link bg-teal-500 block">객실 수정하기</a>
                </div>
                
                <div class="my-5">
                    <a href="{% url 'rooms:delete-room' room.pk %}" class="btn-link bg-red-600 block" >객실 삭제</a> 
                </div>
            {% else %}    
            
            {% if not request.session.is_hosting %}
                    {% for calendar in room.get_calendars  %}
                        <div class="mb-20">
                            <span class="text-center font-semibold text-lg block mb-8">{{calendar.get_month}} / {{calendar.year}}</span>
                            <div class="cal-grid font-medium mb-4">
                                {% for day in calendar.day_names  %}
                                    <span>{{day}}</span>
                                {% endfor %}
                            </div>
                            <div class="cal-grid">
                                {% for day in calendar.get_days  %}
                                    {% is_booked room day as is_booked_bool %}
                                    {% if day.number != 0 %}
                                        {% if day.past %}
                                            <span class="cal-number bg-gray-200 text-gray-400">{{day}}</span>
                                        {% elif is_booked_bool %}
                                            <span class="cal-number bg-gray-200 text-gray-400 line-through ">{{day}}</span>
                                        {% else %}
                                            <a href="{% url 'reservations:create' room.pk day.year day.month day.number %}" class="cal-number bg-gray-200 text-gray-700 hover:bg-teal-400 hover:text-white hover:font-medium">{{day}}</a>
                                        {% endif %}
                                    {% else %}
                                    <span></span>
                                    {% endif %}

                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
               {% endif %}
            {% endif %}
        </div>
    </div>



{% endblock %}

templates/rooms/room_photos.html
{% extends "base.html" %}

{% block page_title %}
{{room.name}}의 사진
{% endblock page_title %}

{% block search-bar %}

{% endblock search-bar %}



{% block content %}

<div class="container mx-auto my-10 flex flex-col  ">
    <div class="my-10 w-full">
        <a href="{% url 'rooms:add-photo' room.pk %}" class="btn-link w-1/6 block">사진 업로드</a>
    </div>
    
    {% for photo in room.photos.all %}
    <div class="mb-5 border p-6 border-gray-400 flex justify-between">
        <div class="flex items-start">
            <img src="{{photo.file.url}}" class="w-32 h-32">
            <span class="ml-5 text-xl">{{photo.caption}}</span>
        </div>
        <div class="flex flex-col w-1/5">
            <a class="btn-link mb-5 bg-teal-500" href="{% url 'rooms:edit-photo' room.pk photo.pk %}">수정</a>
            <a class="btn-link bg-red-600" href="{% url 'rooms:delete-photo' room.pk photo.pk %}">삭제</a> 
        </div>
    </div>    
    {% endfor %}
    
    <div class="flex justify-center mt-5">
        <a href="{% url 'rooms:edit' room.pk %}" class="text-teal-500 font-medium text-xl">객실정보 수정으로 돌아가기</a>
    </div>
    
    
</div>
{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}

{% block page_title %}
검색
{% endblock page_title %}

{% block search-bar %}

{% endblock search-bar %}

<!-- 베이스 탬플릿에 있는 서치바를 숨겨준다 -->

{% block content %}


<h2>검색!</h2>
<form method="get" action="{% url 'rooms:search' %}">

    {{form.as_p}}

    <button>검색</button>
</form>

<h3>검색 결과</h3>

{% for room in rooms %}
<h3>{{room.name}}</h3>
{% endfor %}


<h5>
    {% if rooms.has_previous %}

    <a href="?{{query_string}}&page={{rooms.previous_page_number}}">이전 페이지</a>
    {% endif %}

    페이지 {{rooms.number}} of {{rooms.paginator.num_pages}}

    {% if rooms.has_next %}
    <a href="?{{query_string}}&page={{rooms.next_page_number}}">다음 페이지</a>
    {% endif %}
</h5>

{% endblock content %}