config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    # 장고가 ""인 주소를 보면 , core.urls 로  들어간다
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls",
                                  namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/",
         include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views

app_name = "conversations"

urlpatterns = [
    path("go/<int:a_pk>/<int:b_pk>", views.go_conversation, name="go"),
    path("<int:pk>/", views.ConversationDetailView.as_view(), name="detail"),
]

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path("create/<int:room_pk>/<int:year>-<int:month>-<int:day>", views.create, name="create"),
    # 템플릿에서 전달받은 값들이 순서대로 들어간다
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
]

reservations/models.py
import datetime
from django.db import models
from django.utils import timezone
from core import models as core_models


# Create your models here.
class BookedDay(core_models.TimeStampedModel):
    # 예를들어 15~21일 까지 예약을 했을때 16~20일의 에약 상황을 알수없기에 그것을 알수있는 클래스를 생성한다
    day = models.DateField()
    reservation = models.ForeignKey("Reservation", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "예약일"
        verbose_name_plural = "예약일"


class Reservation(core_models.TimeStampedModel):

    """ 예약 모델 정의 """

    STATUS_PENDING = "진행중"
    STATUS_CONFIRMED = "확정"
    STATUS_CANCELED = "취소"

    STATUS_CHOICES = (
        (STATUS_PENDING, "진행중"),
        (STATUS_CONFIRMED, "확정"),
        (STATUS_CANCELED, "취소"),
    )

    status = models.CharField(
        verbose_name="상태", max_length=32, choices=STATUS_CHOICES, default=STATUS_PENDING
    )
    check_in = models.DateField(verbose_name="체크인")
    check_out = models.DateField(verbose_name="체크아웃")
    guest = models.ForeignKey("users.User", verbose_name="예약자", on_delete=models.CASCADE)
    room = models.ForeignKey(
        "rooms.Room", verbose_name="객실", related_name="reservation", on_delete=models.CASCADE
    )

    def __str__(self):

        return f"예약자 : {self.guest} - 객실 : {self.room} - 예약상태 : {self.status} - 체크인/체크아웃 : {self.check_in}/{self.check_out}"

    def host(self, *args, **kwargs):
        host = self.room.host
        print(host)
        return host

    host.short_description = "호스트"
    # foreignkey 로 가져온 모델의 객체를 표시할때 함수를 이용해보자

    def in_progress(self):
        now = timezone.now().date()

        return now >= self.check_in and now <= self.check_out

    in_progress.boolean = True
    in_progress.short_description = "숙박중"

    def is_finished(self):
        now = timezone.now().date()
        is_finished = now > self.check_out
        if is_finished:
            BookedDay.objects.filter(reservation=self).delete()
        return is_finished

    is_finished.boolean = True
    is_finished.short_description = "숙박종료"

    def save(self, *args, **kwargs):
        # reservation 이 있어야지 BookedDay 가 외래키로 reservation을 받을수 있다 그러므로
        # 세이브를 가로채서 BookedDay를 생성해야한다
        if self.pk is None:
            # 예약 사항이 없다면
            start = self.check_in
            end = self.check_out
            difference = end - start
            existing_booked_day = BookedDay.objects.filter(day__range=(start, end)).exists()
            # BookedDay 에 day가 있기때문에 day__range 를 쓸수있다
            # exists() 를 통해 존재여부를 확인할수있다

            if not existing_booked_day:
                super().save(*args, **kwargs)
                # reservation 이 있어야지 BookedDay 가 외래키로 reservation을 받을수 있다
                for i in range(difference.days + 1):
                    day = start + datetime.timedelta(days=i)
                    # timedelta 시간사이의 간격을 계산할때 사용
                    BookedDay.objects.create(day=day, reservation=self)
                    # 예약일 부터 하루씩 예약을 생성한다
                return
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = "예약"
        verbose_name_plural = "예약"

reservations/views.py
import datetime
from django.http import Http404
from django.views.generic import View
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from rooms import models as room_models
from users import mixins
from reviews import forms as review_forms
from . import models


class CreateError(Exception):
    pass


@login_required
def create(request, room_pk, year, month, day):
    # room_pk, year, month, day 는 템플릿에서 전달받음
    # 나중에 createview 를 이용해 생성해보자
    try:
        date_obj = datetime.datetime(year, month, day)
        room = room_models.Room.objects.get(pk=room_pk)
        models.BookedDay.objects.get(day=date_obj, reservation__room=room)
        # 먼저 예약일과 방이 있는지 찾아본다

    except room_models.Room.DoesNotExist:
        messages.error(request, "객실이 존재하지 않습니다")
        return redirect(reverse("core:home"))

    except models.BookedDay.DoesNotExist:
        reservation = models.Reservation.objects.create(
            guest=request.user,
            room=room,
            check_in=date_obj,
            check_out=date_obj + datetime.timedelta(days=1),
            # 안타깝지만 장고만으로는 예약을 이렇게 밖에 못만든다 , 나중에 react 배워서 다시하자
        )

        return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


class ReservationDetailView(mixins.LoggedInOnlyView, View):
    def get(self, *args, **kwargs):

        pk = kwargs.get("pk")
        reservation = models.Reservation.objects.get_or_none(pk=pk)
        if not reservation or (
            reservation.guest != self.request.user and reservation.room.host != self.request.user
        ):  # 예약한 게스트가 접속한 유저가 아니고 호스트도 아니면
            raise Http404("페이지를 찾을수 없습니다")
        form = review_forms.CreateReviewForm()
        # 예약이 확정되고 숙박이 종료되면 리뷰를 작성할수있게 폼을 넘겨준다

        return render(
            self.request, "reservations/detail.html", {"reservation": reservation, "form": form}
        )


# @login_required
# def get(request, *args, **kwargs):
#     pk = kwargs.get("pk")
#     reservation = models.Reservation.objects.get_or_none(pk=pk)
#     if not reservation or (
#         reservation.guest != request.user and reservation.room.host != request.user
#     ):
#         raise Http404("페이지를 찾을수 없습니다")
#     form = review_forms.CreateReviewForm()
#     return render(request, "reservations/detail.html", {"reservation": reservation, "form": form})
# 이런식으로 FBV 로 작성해도 된다


@login_required
# cbv 는 믹스인 fbv은 데코레이터!! 잘 써먹자
def edit_reservation(request, pk, verb):
    # 템플릿에서 pk, verb 를 전달받는다
    reservation = models.Reservation.objects.get_or_none(pk=pk)
    # 매니저를 사용함으로서 존재하는지 여부를 간단하게 표시가능
    if not reservation or (
        reservation.guest != request.user and reservation.room.host != request.user
    ):
        raise Http404("페이지를 찾을수 없습니다")
    if verb == "confirm":
        reservation.status = models.Reservation.STATUS_CONFIRMED
    if verb == "cancel":
        reservation.status = models.Reservation.STATUS_CANCELED
        models.BookedDay.objects.filter(reservation=reservation).delete()
        messages.success(request, "예약을 취소 하였습니다")
        reservation.save()
        return redirect(reverse("rooms:detail", kwargs={"pk": reservation.pk}))
        # 예약을 삭제하면 예약일도 지워야한다

    reservation.save()
    messages.success(request, "예약을 업데이트 하였습니다")
    return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))

templates/reservations/detail.html
{% extends "base.html" %}

{% block page_title %}
    예약 {{reservation.check_in}}
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container mx-auto my-10 flex flex-col">

        <div class="border-t border-l border-r bg-cover bg-center h-56 rounded-t-lg" style="background-image: url({{reservation.room.first_photo}});"></div>

        <div class="flex flex-col items-start border-l border-r border-t border-b">
            <div class="font-medium border-b py-8 px-5 w-full">
                {{reservation.check_in}} - {{reservation.check_out}} <span class="ml-5 {% if reservation.status == '진행중' %} text-yellow-500 {% elif reservation.status == '취소' %} text-red-600 {% else %} text-teal-600 {% endif %}">{{reservation.get_status_display}}</span>

            </div>

            <span class="text-2xl border-b p-5 mt-2 w-full">
                {{reservation.room.name}}
            </span>

            <div class="flex p-5 border-b w-full">
                <div class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user=reservation.room.host %}
                    <span class="mt-2 text-gray-500">{{reservation.room.host.first_name}}</span>
                </div>
                <div class="ml-5 flex flex-col">
                    <span class="font-medium mb-px">호스트에게 연락해보세요</span>
                    <a href="{% url 'conversations:go' reservation.room.host.pk reservation.guest.pk %}" class="font-medium text-teal-500">메시지 보내기</a>
                </div>       
            </div>

            <div class="py-10 px-5">    
                {% if reservation.status != '취소' %}
                {% if reservation.status == '확정' and reservation.is_finished %}
                    <span class="font-medium text-2xl text-center w-full block mb-5">리뷰를 작성 해주세요</span>
                   <form action="{% url 'reviews:create' reservation.room.pk %}" method="POST" class="w-1/2 mx-auto">
                       {% csrf_token %}
                       {{form}}
                       <button class="btn-link mt-5">리뷰작성</button>
                   </form>
                {% else %}
                        {% if reservation.status == '진행중' %}
                            <a href="{% url 'reservations:edit' reservation.pk 'cancel' %}" class="btn-link block px-5">예약취소</a>
                            {% if reservation.room.host == user  %}
                                <a href="{% url 'reservations:edit' reservation.pk 'confirm' %}" class="btn-link block px-3 mb-5">예약확인</a>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}