config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    # 장고가 ""인 주소를 보면 , core.urls 로  들어간다
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls",
                                  namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/",
         include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

users/urls.py
from django.urls import path
from . import views


app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao-callback"),
    path("login/google/", views.google_login, name="google-login"),
    path("login/google/callback/", views.google_callback, name="google-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>/", views.complete_verification, name="complete-verification"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswowdView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . import models


class LoginForm(forms.Form):

    email = forms.EmailField(label="이메일", widget=forms.EmailInput(attrs={"placeholder": "이메일"}))
    password = forms.CharField(
        label="비밀번호", widget=forms.PasswordInput(attrs={"placeholder": "비밀번호"})
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("비밀번호가 틀립니다"))

        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("존재하지 않는 사용자입니다"))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("last_name", "first_name", "email")
        widgets = {
            "last_name": forms.TextInput(attrs={"placeholder": "성"}),
            "first_name": forms.TextInput(attrs={"placeholder": "이름"}),
            "email": forms.EmailInput(attrs={"placeholder": "이메일"}),
        }

    password = forms.CharField(
        label="비밀번호", widget=forms.PasswordInput(attrs={"placeholder": "비밀번호"})
    )
    password1 = forms.CharField(
        label="비밀번호 확인", widget=forms.PasswordInput(attrs={"placeholder": "비밀번호 확인"})
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")

        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError("이미 존재하는 사용자 입니다", code="existing_user")
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError("비밀번호가 서로 일치하지 않습니다")
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        # commit=False를 하게 되면 데이터베이스에 당장 저장하지 않는다.
        # 언제쓰지? : DB에 데이터를 저장하기 전에 특정 행위를 하고 싶을 때 사용한다
        # 저장을 늦게 시켜서 사용자가 원하는 추가적인 정보를 저장할 수 있는 것이라고 생각하면 된다
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()

users/views.py
import os
import requests
from django.utils import translation
from django.http import HttpResponse
from django.conf import settings

# import google.oauth2.credentials
# import google_auth_oauthlib.flow
from django.views import View
from django.views.generic import FormView, DetailView, UpdateView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeView
from django.core.files.base import ContentFile
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required

from . import forms, models, mixins

# Create your views here.


class LoginView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/login.html"
    form_class = forms.LoginForm

    # success_url = reverse_lazy("core:home")

    def form_valid(self, form):

        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)

        # authenticate =>주어진 자격 증명이 유효하면 User 객체를 반환합니다.
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)
        # return super().form_valid(form) 의 기능은
        # form_valid 함수를 통해서 cleaned_data 관련 로직을 수행하고 성공적으로 마치면
        # 알아서 success_url에서 정의한 페이지로 폼과 함께 이동해준다

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next is not None:
            return next_arg
        # 로그인 되지 않은 상태에서 LoggedInOnlyView 에 접근하면 나오는 페이지에서 다시 로그인을 하면
        # next_arg 로 계속 진행
        else:
            return reverse("core:home")


def log_out(request):

    messages.info(request, f"{request.user.username}님 이용해 주셔서 감사합니다")
    logout(request)

    return redirect(reverse("core:home"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        # authenticate =>주어진 자격 증명이 유효하면 User 객체를 반환합니다.
        if user is not None:
            login(self.request, user)
        user.verify_email()
        return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
        # 성공 메시지 추가할것
    except models.User.DoesNotExist:
        # 에러 메시지 추가할것
        pass
    return redirect(reverse("core:home"))


# 유저들은 깃허브 아이덴티티를 요청하기위해 깃허브로 리다이렉트 된다
# 유저들을 깃허브에 의해 다시 웹사이트로 리다이렉트 된다
# 유저의 억세스 토큰으로 유저의 정보 api를 받을수 있다 (토큰은 깃허브의 코드와 교환한다 ,그걸 교환하는 함수가 콜백함수)
# 깃허브 콜백 함수를 통해 우리사이트에 로그인 시킨다
# https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/ 참조


def github_login(request):
    client_id = os.environ.get("GH_ID")
    redirect_uri = "https://mybnbbnb.herokuapp.com/users/login/github/callback"
    return redirect(
        f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user"
    )


class GithubException(Exception):
    pass


def github_callback(request):
    try:
        client_id = os.environ.get("GH_ID")
        client_secret = os.environ.get("GH_SECRET")
        code = request.GET.get("code", None)

        if code is not None:
            token_request = requests.post(
                f"https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"},
                # requests 라이브러리를 이용해서 코드와 토큰을 교환해 json을 받아온다
                # HTTP 헤더는 클라이언트와 서버가 요청 또는 응답으로 부가적인 정보를 전송할 수 있도록 해줍니다
            )
            token_json = token_request.json()
            error = token_json.get("error", None)
            # json 의 에러를 체크한다

            if error is not None:
                # 에러가 있다면
                raise GithubException("토큰에 접근할 수 없습니다")
            else:
                access_token = token_json.get("access_token")
                profile_request = requests.get(
                    "https://api.github.com/user",
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )
                # access_token을 통해 api를 받아온다
                profile_json = profile_request.json()
                # profile_json 을 받아온다
                username = profile_json.get("login", None)

                if username is not None:
                    name = profile_json.get("login")

                    try:
                        user = models.User.objects.get(username=name)
                        if user.login_method == models.User.LOGIN_EMAIL:
                            raise GithubException(
                                f"이미 가입된 회원입니다 이메일과 비밀번호 입력을 통해 로그인을 해주세요 ")
                        if user.login_method == models.User.LOGIN_KAKAO:
                            raise GithubException(
                                f"이미 가입된 회원입니다 카카오로 로그인을 해주세요 ")
                        if user.login_method == models.User.LOGIN_GOOGLE:
                            raise GithubException(
                                f"이미 가입된 회원입니다 구글로 로그인을 해주세요 ")

                    except models.User.DoesNotExist:
                        user = models.User.objects.create(
                            username=name,
                            login_method=models.User.LOGIN_GITHUB,
                        )
                        user.set_unusable_password()
                        user.save()
                    login(request, user)
                    messages.success(request, f"{user.username} 님 반갑습니다")
                    return redirect(reverse("core:home"))
                else:
                    raise GithubException("프로필을 불러올수 없습니다")
        else:
            raise GithubException("인증코드를 받을수없습니다")

    except GithubException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


def kakao_login(request):
    app_key = os.environ.get("KAKAO_KEY")
    redirect_uri = "https://mybnbbnb.herokuapp.com/users/login/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={app_key}&redirect_uri={redirect_uri}&response_type=code"
    )


class KakaoException(Exception):
    pass


def kakao_callback(request):
    try:
        app_key = os.environ.get("KAKAO_KEY")
        code = request.GET.get("code")
        redirect_uri = "https://mybnbbnb.herokuapp.com/users/login/kakao/callback"
        post_data = {
            "grant_type": "authorization_code",
            "client_id": app_key,
            "redirect_uri": redirect_uri,
            "code": code,
        }
        token_request = requests.post(f"https://kauth.kakao.com/oauth/token",
                                      data=post_data)
        token_json = token_request.json()
        error = token_json.get("error", None)

        if error is not None:
            raise KakaoException("인증코드를 받을수 없습니다")
        else:
            access_token = token_json.get("access_token")
            profile_request = requests.get(
                "https://kapi.kakao.com/v2/user/me",
                headers={"Authorization": f"Bearer {access_token}"},
            )

            profile_json = profile_request.json()

            kakao_account = profile_json.get("kakao_account")
            properties = profile_json.get("properties")
            profile = kakao_account.get("profile")
            email = kakao_account.get("email", None)
            if email is None:
                raise KakaoException("이메일 주소를 입력 바랍니다")
            nickname = properties.get("nickname")
            profile_image = properties.get("profile_image")

            try:
                user = models.User.objects.get(username=nickname)
                if user.login_method == models.User.LOGIN_EMAIL:
                    raise KakaoException(
                        f"이미 가입된 회원입니다 이메일과 비밀번호 입력을 통해 로그인을 해주세요 ")
                if user.login_method == models.User.LOGIN_GITHUB:
                    raise KakaoException(f"이미 가입된 회원입니다 깃허브로 로그인을 해주세요 ")
                if user.login_method == models.User.LOGIN_GOOGLE:
                    raise KakaoException(f"이미 가입된 회원입니다 구글로 로그인을 해주세요 ")
            except models.User.DoesNotExist:
                user = models.User.objects.create(
                    username=nickname,
                    email=email,
                    login_method=models.User.LOGIN_KAKAO,
                )
                user.set_unusable_password()
                user.save()

                if profile_image is not None:
                    photo_request = requests.get(profile_image)

                    user.avatar.save(f"{nickname}-사진",
                                     ContentFile(photo_request.content))
            login(request, user)
            messages.success(request, f"{user.username} 님 반갑습니다")
            return redirect(reverse("core:home"))
    except KakaoException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


def google_login(reguest):
    client_id = os.environ.get("GOOGLE_ID")
    redirect_uri = "https://mybnbbnb.herokuapp.com/users/login/google/callback"
    return redirect(
        f"https://accounts.google.com/o/oauth2/v2/auth?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code&scope=https://www.googleapis.com/auth/userinfo.email&access_type=offline"
    )


class GoogleException(Exception):
    pass


def google_callback(request):
    try:

templates/users/login.html
{% extends "base.html" %}

{% block page_title %}
로그인
{% endblock page_title %}

{% block search-bar %}

{% endblock search-bar %}

<!-- 베이스 탬플릿에 있는 서치바를 숨겨준다 -->

{% block content %}

<div class="container xl:w-1/4 lg:w-5/12 md:w-1/2  mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
    {% include 'partials/social_login.html' %}


    {% include 'mixins/auth/auth_form.html' with form=form cta="로그인" %}


    <div class="mt-5 ">
        <span class=" mr-2">계정이 없으신가요?</span><a href="{% url 'users:signup' %}" class=" font-bold">회원가입</a>
    </div>
    

</div>
{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}

{% block page_title %}
회원가입
{% endblock page_title %}

{% block search-bar %}

{% endblock search-bar %}

<!-- 베이스 탬플릿에 있는 서치바를 숨겨준다 -->

{% block content %}


<div class="container xl:w-1/4 lg:w-5/12 md:w-1/2  mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
    {% include 'partials/social_login.html' %}
        {% include 'mixins/auth/auth_form.html' with form=form cta="회원가입" %}

    
    <div class="mt-5 ">
        <span class=" mr-2">이미 계정이 있으신가요?</span><a href="{% url 'users:login' %}" class=" font-bold">로그인</a>
    </div>
</div>

{% endblock content %}

templates/users/update-password.html
{% extends "base.html" %}

{% block page_title %}
비밀번호 수정
{% endblock page_title %}

{% block search-bar %}

{% endblock search-bar %}

<!-- 베이스 탬플릿에 있는 서치바를 숨겨준다 -->

{% block content %}

<div class="min-h-75vh">
    <div class="container xl:w-1/4 lg:w-5/12 md:w-1/2  mx-auto my-10 flex flex-col items-center border  border-gray-400 p-6">
  
        {% include 'mixins/auth/auth_form.html' with form=form cta="비밀번호 변경" %}
    
        
    </div>
</div>

{% endblock content %}

templates/users/update-profile.html
{% extends "base.html" %}

{% block page_title %}
프로필 수정
{% endblock page_title %}

{% block search-bar %}

{% endblock search-bar %}

<!-- 베이스 탬플릿에 있는 서치바를 숨겨준다 -->

{% block content %}

<div class="container xl:w-1/4 lg:w-5/12 md:w-1/2  mx-auto my-10 flex flex-col items-center border  border-gray-400 p-6">
  
    {% include 'mixins/auth/auth_form.html' with form=form cta="프로필 업데이트" %}
    
    {% if object.login_method == "email" %}
    <div class="mt-5 ">
        <a href="{% url 'users:password' %}" class="font-medium">비밀번호 변경</a>
    </div>
    {% endif %}
    
</div>
{% endblock content %}

<!-- 플레이스 홀더를 입력하려면 직접 폼을 커스텀해야한다  -->

templates/users/user_detail.html
{% extends "base.html" %}

{% block page_title %}
    {{user_obj.username}}의 정보
{% endblock page_title %}



{% block content %}



<div class="min-h-75vh">
    <div class="container xl:w-1/4 lg:w-5/12 md:w-1/2  mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include "mixins/user_avatar.html" with user=user_obj %}
        
            <div class="flex items-center">
                <span class="text-3xl mt-1">{{user_obj.username}}</span>
            </div>
            {% if user_obj.superhost %}
            <div class="flex items-center">
                <span class="mr-2 my-2 font-bold text-xs text-blue-600 border border-blue-600 rounded-md py-1 px-1">
                    슈퍼호스트</span>
            </div>
    
            {% endif %}
        
    
        <span class="text-lg mb-5">{{user_obj.bio}}</span>
        
        {% if user == user_obj %}
        <a href="{% url 'users:update' %}" class="btn-link">프로필 수정</a>
        {% endif %}
        
    
    </div>
    {% if user_obj.rooms.count > 0 %}
    <h3 class="mb-12 text-2xl text-center">{{user_obj.username}}님이 운영중인 객실</h3>
    <div class="container mx-auto pb-10 ">
        <div class="flex flex-wrap -mx-40 mb-10">
            {% for room in user_obj.rooms.all  %}
                {% include 'mixins/room_card.html' with room=room %}
            {% endfor %}
        </div>
    </div>
    {% endif %}
</div>

{% endblock content %}